spring.datasource.url=jdbc:postgresql://201.34.143.129:5432/workdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=work
spring.datasource.password=M%2Qx22146
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080